
@baseURL = http://localhost:4000
@id = 619afa6296dedf07c599b778
###
// GET - Lista todos os registros
GET {{baseURL}}/academia
Content-Type: application/json

###
// GET - Por ID
GET {{baseURL}}/academia/{{id}}
Content-Type: application/json

###
// POST
POST {{baseURL}}/academia
Content-Type: application/json

{
   "nome":"Fabiana Marques Silva",
   "dataNascimento": "09/03/2001",
   "endereco": {
      "logradouro":"Rua São Paulo",
      "bairro":"Itu",
      "numero": 123
      },
   "plano": "Anual",
   "instrutor": "Diogo",
   "dataInscricao": "30/03/2021",
   "dataVencimento": "30/03/2022"

}

### 
// DELETE
DELETE {{baseURL}}/academia/{{id}}
Content-Type: application/json

###
// PUT
PUT {{baseURL}}/academia/
Content-Type: application/json

{
   "_id": "619afa6296dedf07c599b778", 
   "nome":"Antonio",
   "dataNascimento": "09/03/2001",
   "endereco": {
      "logradouro":"Av.Tiradentes",
      "bairro":"Itu",
      "numero": 123
      },
   "plano": "Anual",
   "instrutor": "Diogo",
   "dataInscricao": "30/03/2021",
   "dataVencimento": "30/03/2022"
}


